# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='Institucional',
        ),
    ]
