# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20170918_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucional',
            name='descricaoFeriado',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
