# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_institucional_descricaoferiado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='institucional',
            name='id',
        ),
        migrations.AddField(
            model_name='institucional',
            name='agenda_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agenda.Agenda'),
            preserve_default=False,
        ),
    ]
