# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20170918_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institucional',
            old_name='descricaoFeriado',
            new_name='descricao_Do_Feriado',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='ok',
        ),
        migrations.RemoveField(
            model_name='institucional',
            name='dataEHoraDeInicio',
        ),
        migrations.RemoveField(
            model_name='institucional',
            name='nome',
        ),
        migrations.AddField(
            model_name='agenda',
            name='data_e_hora_de_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='nome',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
