# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20170918_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('data_e_hora_de_inicio', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('local', models.TextField()),
            ],
        ),
    ]
