# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_compromisso'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='agenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda'),
            preserve_default=False,
        ),
    ]
