# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_publica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='nome',
            new_name='nome_Da_Agenda',
        ),
        migrations.RenameField(
            model_name='publica',
            old_name='descricao_Do_Feriado',
            new_name='descricao_Da_Agenda',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='data_e_hora_de_inicio',
        ),
    ]
