# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_auto_20170918_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucional',
            name='agenda_ptr',
        ),
        migrations.RemoveField(
            model_name='institucional',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='publica',
            name='agenda_ptr',
        ),
        migrations.RemoveField(
            model_name='publica',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Institucional',
        ),
        migrations.DeleteModel(
            name='Publica',
        ),
    ]
