# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_institucional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucional',
            name='descricao_Do_Feriado',
        ),
    ]
