# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_privada'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='institucional',
            name='agenda_ptr',
        ),
        migrations.RemoveField(
            model_name='institucional',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='privada',
            name='agenda_ptr',
        ),
        migrations.RemoveField(
            model_name='privada',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='publica',
            name='agenda_ptr',
        ),
        migrations.RemoveField(
            model_name='publica',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='nome_Da_Agenda',
            new_name='institucional',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Institucional',
        ),
        migrations.DeleteModel(
            name='Privada',
        ),
        migrations.DeleteModel(
            name='Publica',
        ),
        migrations.AddField(
            model_name='agendausuario',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda'),
        ),
        migrations.AddField(
            model_name='agendausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agenda.Tipo'),
            preserve_default=False,
        ),
    ]
