# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_auto_20170925_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='visivel',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
