# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_agenda_visivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='nome',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
