# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_agenda_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='institucional',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='visivel',
        ),
    ]
