# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_auto_20170925_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendausuario',
            name='agenda',
        ),
        migrations.AddField(
            model_name='agendausuario',
            name='compromisso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agenda.Compromisso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nome',
            field=models.CharField(max_length=15),
        ),
    ]
