# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_auto_20170925_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgendaUsuario',
            new_name='CompromissoUsuario',
        ),
    ]
