# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_auto_20170925_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromissousuario',
            name='compromisso',
        ),
        migrations.RemoveField(
            model_name='compromissousuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='compromisso',
            name='usuario',
            field=models.ManyToManyField(to='agenda.Usuario'),
        ),
        migrations.DeleteModel(
            name='CompromissoUsuario',
        ),
    ]
