# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0021_auto_20170925_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromisso',
            name='descricao',
        ),
    ]
