# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0022_remove_compromisso_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CompromissoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='compromisso',
            name='usuario',
        ),
        migrations.AddField(
            model_name='compromisso',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compromissousuario',
            name='compromisso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Compromisso'),
        ),
        migrations.AddField(
            model_name='compromissousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario'),
        ),
    ]
